openapi: "3.0.0"
info:
  version: "0.0.1"  # x-release-please-version
  title: Manage stuff you own
paths:
  /models:
    get:
      responses:
        '200':
          description: Model list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelCollection'

  /vendors:
    get:
      responses:
        '200':
          description: Vendor list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VendorCollection'

components:
  schemas:
    Vendor:
      type: object
      required:
        - id
        - name
        - created_at
        - updated_at
      properties:
        id:
          type: integer
          description: A unique identifier for the vendor.
        name:
          type: string
          description: A readable name for the vendor.
          example: Acme Inc.
        created_at:
          type: string
          format: date-time
          description: The instant the vendor was added to the system.
        updated_at:
          type: string
          format: date-time
          description: The instant the vendor's information was last updated.


    ModelCollection:
      type: object
      required:
        - ping
      properties:
        ping:
          type: string
          example: pong

    VendorCollection:
      type: object
      required:
        - items
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Vendor'
