volumes:
  database:

services:
  db:
    image: postgres:17

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      # Required for the health check to not spam `role "root" does not exist
      PGUSER: postgres

    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

    volumes:
      - database:/var/lib/postgresql/data

  api-migrate:
    build:
      context: api
      dockerfile: Dockerfile

    command: ["migrate"]

    environment:
      STUFF_DSN: postgres://postgres:password@db/postgres

    depends_on:
      db:
        condition: service_healthy

  api:
    build:
      context: api
      dockerfile: Dockerfile

    environment:
      STUFF_DSN: postgres://postgres:password@db/postgres

    depends_on:
      api-migrate:
        condition: service_completed_successfully

  web:
    build:
      context: web
      dockerfile: Dockerfile

    environment:
      API_BASE_URL: http://api:8080

    ports:
      - 3030:3000
