on:
  pull_request:
    branches:
      - main
    paths:
      - 'api/**'

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Generate code
        run: go generate ./...
        working-directory: api

      - name: Ensure generated code is up to date
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Generated files have differences:"
            git status
            git diff
            exit 1
          fi
