on:
  pull_request:
    branches:
      - main
    paths:
      - 'web/**'

  push:
    branches:
      - main
    paths:
      - 'web/**'

jobs:
  test-web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: web/package-lock.json
          node-version: 22

      - name: Install dependencies
        run: npm ci
        working-directory: web

      - name: Check style
        run: npm run check-style
        working-directory: web

      - name: Lint code
        run: npm run lint
        working-directory: web
