on:
  pull_request:
    branches:
      - main
    paths:
      - "web/**"

  push:
    branches:
      - main
    paths:
      - "api.yaml"
      - "web/**"

name: web

jobs:
  test-web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: web/package-lock.json
          node-version: 22

      - name: Install dependencies
        run: npm ci
        working-directory: web

      - name: Check style
        run: npm run check-style
        working-directory: web

      - name: Lint code
        run: npm run lint
        working-directory: web

      - name: Generate code
        run: npm run generate-api-client
        working-directory: web

      - name: Ensure generated code is up to date
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Generated files have differences:"
            git status
            git diff
            exit 1
          fi
